import { buildPrompt } from './prompts.js';

const DEFAULT_TEXT_MODEL='@cf/zai-org/glm-4.7-flash';
const DEFAULT_IMAGE_MODEL='@cf/black-forest-labs/flux-1-schnell';
const MAX_BODY=900_000;
const TEXT_EXT=/\.(?:html?|css|js|mjs|cjs|ts|tsx|jsx|json|md|txt|xml|csv)$/i;
const ASSET_EXT=/\.(?:html?|css|js|mjs|cjs|ts|tsx|jsx|json|md|txt|xml|csv|png|jpe?g|webp|gif|svg|ico|avif|woff2?|ttf|mp3|wav|ogg|mp4|webm|pdf)$/i;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function withTimeout(promise,ms,label='操作'){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`${label}超过 ${Math.round(ms/1000)} 秒`)),ms);})]);}finally{clearTimeout(timer);}}
async function fetchWithTimeout(url,options={},timeoutMs=12000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal});}catch(e){if(e?.name==='AbortError')throw new Error(`网络请求超过 ${Math.round(timeoutMs/1000)} 秒：${new URL(url).hostname}`);throw e;}finally{clearTimeout(timer);}}

function corsHeaders(request,env){const origin=request.headers.get('Origin')||'';const allowed=String(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);const ok=!allowed.length||allowed.includes(origin)||/^https:\/\/[^/]+\.github\.io$/.test(origin)||/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);return{'Access-Control-Allow-Origin':ok?(origin||'*'):'null','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Agent-Key','Access-Control-Max-Age':'86400','Vary':'Origin','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};}
function json(request,env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(request,env),'content-type':'application/json; charset=utf-8'}});}
function authorized(request,env){return !env.APP_SECRET||request.headers.get('X-Agent-Key')===env.APP_SECRET;}
async function readJson(request){const len=Number(request.headers.get('content-length')||0);if(len>MAX_BODY)throw new Error('请求过大');const text=await request.text();if(text.length>MAX_BODY)throw new Error('请求过大');return text?JSON.parse(text):{};}
function getText(result){if(!result)return'';if(typeof result==='string')return result;if(typeof result.response==='string')return result.response;if(typeof result.result==='string')return result.result;const c=result.choices?.[0]?.message?.content;if(typeof c==='string')return c;if(Array.isArray(c))return c.map(x=>x.text||x.content||'').join('');return JSON.stringify(result,null,2);}
async function runText(env,prompt,opts={}){if(!env.AI)throw new Error('缺少 Workers AI binding：请在 wrangler.jsonc 配置 AI');const model=env.TEXT_MODEL||DEFAULT_TEXT_MODEL;const messages=[{role:'system',content:'你是专门服务网页叙事解谜制作流程的专业 Agent。严格遵守项目方法论，拒绝模板化空话。'},{role:'user',content:prompt}];const timeoutMs=Math.max(15000,Math.min(120000,Number(opts.timeoutMs||env.AI_TIMEOUT_MS)||90000));const result=await withTimeout(env.AI.run(model,{messages,max_completion_tokens:opts.maxTokens||Number(env.MAX_TOKENS)||9000,temperature:opts.temperature??0.45}),timeoutMs,'Workers AI');return{text:getText(result),model};}
function parseJsonText(text){let t=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(t);}catch{}const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a){try{return JSON.parse(t.slice(a,b+1));}catch{}}return null;}
async function runJson(env,task,payload,opts={}){const r=await runText(env,buildPrompt(task,payload),{temperature:opts.temperature??.2,maxTokens:opts.maxTokens||7000,timeoutMs:opts.timeoutMs});const data=parseJsonText(r.text);if(!data)throw new Error('AI 未返回有效结构化 JSON');return{data,model:r.model};}
function sanitizeBlindReview(v){const x=v&&typeof v==='object'?v:{};const score=Number(x.score),confidence=Number(x.confidence),sev=new Set(['P0','P1','P2','P3']),dec=new Set(['fix','consider','keep']);const findings=(Array.isArray(x.findings)?x.findings:[]).filter(Boolean).slice(0,36).map(f=>({...f,severity:sev.has(f.severity)?f.severity:'P2',decision:dec.has(f.decision)?f.decision:'consider'}));return{score:Number.isFinite(score)?Math.max(0,Math.min(10,score)):null,confidence:Number.isFinite(confidence)?Math.max(0,Math.min(1,confidence)):0,summary:String(x.summary||''),strengths:Array.isArray(x.strengths)?x.strengths.slice(0,12):[],findings,preserve:Array.isArray(x.preserve)?x.preserve.slice(0,12):[],blindSpots:Array.isArray(x.blindSpots)?x.blindSpots.slice(0,16):[]};}

function parseRepoUrl(url){const m=String(url||'').match(/^https?:\/\/github\.com\/([^/]+)\/([^/#?]+)(?:[/?#].*)?$/i);if(!m)throw new Error('仅支持标准 GitHub 仓库地址');return{owner:m[1],repo:m[2].replace(/\.git$/,'')};}
function ghHeaders(env){const h={'Accept':'application/vnd.github+json','User-Agent':'narrative-workshop-agent','X-GitHub-Api-Version':'2022-11-28'};if(env.GITHUB_TOKEN)h.Authorization=`Bearer ${env.GITHUB_TOKEN}`;return h;}
async function ghFetch(url,env){let last;for(let attempt=0;attempt<2;attempt++){let r;try{r=await fetchWithTimeout(url,{headers:ghHeaders(env)},15000);}catch(e){last=e;if(attempt===0){await sleep(650);continue;}throw e;}if(r.ok)return r.json();const t=await r.text();const remaining=r.headers.get('x-ratelimit-remaining'),reset=Number(r.headers.get('x-ratelimit-reset')||0);if((r.status===403||r.status===429)&&remaining==='0'){const when=reset?new Date(reset*1000).toLocaleString('zh-CN'):'稍后';throw new Error(`GitHub API 额度已用尽，预计 ${when} 后恢复`);}last=new Error(`GitHub API ${r.status}: ${t.slice(0,180)}`);if(attempt===0&&(r.status===429||r.status>=500)){await sleep(900);continue;}throw last;}throw last||new Error('GitHub API 请求失败');}
function encPath(path){return path.split('/').map(encodeURIComponent).join('/');}
function dirname(path){const i=path.lastIndexOf('/');return i<0?'':path.slice(0,i);}
function normalizePath(path){const out=[];for(const part of String(path).split('/')){if(!part||part==='.')continue;if(part==='..')out.pop();else out.push(part);}return out.join('/');}
function resolveRef(from,ref,treeSet){let raw=String(ref||'').trim();if(!raw||/^(?:https?:|data:|mailto:|tel:|javascript:|#|\/\/)/i.test(raw))return null;raw=raw.replace(/[?#].*$/,'').replace(/^\.\//,'');try{raw=decodeURIComponent(raw);}catch{}let p=raw.startsWith('/')?raw.slice(1):normalizePath(`${dirname(from)}/${raw}`);if(treeSet.has(p))return p;if(treeSet.has(`${p}/index.html`))return`${p}/index.html`;return p&&ASSET_EXT.test(p)?p:null;}
function extractRefs(path,text){const refs=new Set();const add=x=>{if(x&&x.length<500)refs.add(x.trim())};let m;
  const attrs=/(?:src|href|data-src|poster|content)\s*=\s*["']([^"']+)["']/gi;while((m=attrs.exec(text)))add(m[1]);
  const imports=/(?:import\s*(?:[^'"()]+?\sfrom\s*)?|import\s*\(|require\s*\(|fetch\s*\(|window\.open\s*\(|location(?:\.href)?\s*=)\s*["']([^"']+)["']/gi;while((m=imports.exec(text)))add(m[1]);
  const css=/(?:url\(|@import\s+)["']?([^"')\s;]+)["']?\)?/gi;while((m=css.exec(text)))add(m[1]);
  const strings=/["']([^"'\n]{1,220}\.(?:html?|css|js|mjs|ts|json|png|jpe?g|webp|gif|svg|ico|avif|woff2?|ttf|mp3|wav|ogg|mp4|webm|pdf)(?:[?#][^"']*)?)["']/gi;while((m=strings.exec(text)))add(m[1]);
  return [...refs];
}
async function getRepoBase(owner,repo,env){const meta=await ghFetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`,env);const branch=meta.default_branch||'main';const tree=await ghFetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/trees/${encodeURIComponent(branch)}?recursive=1`,env);const blobs=(tree.tree||[]).filter(x=>x.type==='blob');return{meta,branch,revision:tree.sha||branch,blobs,treeTruncated:!!tree.truncated};}
async function fetchRaw(owner,repo,branch,path,env){const u=`https://raw.githubusercontent.com/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/${encodeURIComponent(branch)}/${encPath(path)}`;const headers={'User-Agent':'narrative-workshop-agent'};if(env?.GITHUB_TOKEN)headers.Authorization=`Bearer ${env.GITHUB_TOKEN}`;for(let attempt=0;attempt<2;attempt++){try{const r=await fetchWithTimeout(u,{headers},10000);if(r.ok)return(await r.text()).slice(0,120000);if(r.status===404)return null;if(attempt===0&&r.status>=500){await sleep(500);continue;}return null;}catch(e){if(attempt===0){await sleep(500);continue;}return null;}}return null;}
function chooseEntries(blobs){const paths=blobs.map(x=>x.path),set=new Set(paths),entries=[];for(const c of ['index.html','index.htm','site/index.html','docs/index.html','public/index.html','dist/index.html','www/index.html','game/index.html','src/index.html'])if(set.has(c))entries.push(c);if(!entries.length){const html=paths.filter(p=>/\.html?$/i.test(p)).sort((a,b)=>a.split('/').length-b.split('/').length||a.length-b.length);entries.push(...html.slice(0,6));}return[...new Set(entries)];}
function countMatches(text,re){const m=String(text||'').match(re);return m?m.length:0;}
function interactionSignals(joined){
  const absoluteRefs=countMatches(joined,/(?:src|href)\s*=\s*["']\/(?!\/)|(?:fetch|window\.open)\s*\(\s*["']\/(?!\/)|location(?:\.href)?\s*=\s*["']\/(?!\/)/gi);
  const buttons=countMatches(joined,/<button\b/gi),links=countMatches(joined,/<a\b/gi),inputs=countMatches(joined,/<(?:input|textarea|select)\b/gi),forms=countMatches(joined,/<form\b/gi);
  const clickHandlers=countMatches(joined,/addEventListener\s*\(\s*["']click["']|\.onclick\s*=|onclick\s*=/gi),submitHandlers=countMatches(joined,/addEventListener\s*\(\s*["']submit["']|\.onsubmit\s*=|onsubmit\s*=/gi);
  return{buttons,links,inputs,forms,clickHandlers,submitHandlers,dragDrop:/dragstart|dragover|drop\b|draggable\s*=/.test(joined),touch:/touchstart|touchmove|pointerdown|pointermove/.test(joined),keyboard:/keydown|keyup|keypress/.test(joined),locationChanges:countMatches(joined,/location(?:\.href)?\s*=|window\.open\s*\(/gi),storageWrites:countMatches(joined,/(?:localStorage|sessionStorage)\.setItem\s*\(|indexedDB\.open\s*\(/gi),absoluteRootRefs:absoluteRefs,emptyHref:countMatches(joined,/href\s*=\s*["'](?:#|javascript:[^"']*)["']/gi)};
}
function autoSignals(files,referenced,blobs){const joined=files.map(f=>f.content).join('\n');return{reachableTextFiles:files.length,referencedFiles:referenced.size,totalRepoFiles:blobs.length,htmlFiles:[...referenced].filter(x=>/\.html?$/i.test(x)).length,cssFiles:[...referenced].filter(x=>/\.css$/i.test(x)).length,imageFiles:[...referenced].filter(x=>/\.(?:png|jpe?g|webp|gif|svg|avif)$/i.test(x)).length,hasResponsive:/@media\s*\(/i.test(joined),hasLocalStorage:/localStorage|sessionStorage|indexedDB/i.test(joined),hasPayment:/付款|支付|二维码|donate|payment/i.test(joined),hasGlitch:/glitch|故障|噪点|scanline/i.test(joined),hasLockedLanguage:/未解锁|第[一二三四五六七八九十\d]+章|完成上一关/.test(joined),hasAiCliche:/你不该来这里|有些事情最好不要知道|真相从未消失/.test(joined),titles:[...joined.matchAll(/<title[^>]*>([^<]{1,100})<\/title>/gi)].slice(0,8).map(m=>m[1].trim()),interaction:interactionSignals(joined)};}
async function inspectRepo(owner,repo,env){const{meta,branch,revision,blobs,treeTruncated}=await getRepoBase(owner,repo,env);const treeSet=new Set(blobs.map(x=>x.path)),blobMap=new Map(blobs.map(x=>[x.path,x]));const entries=chooseEntries(blobs);const queue=[...entries],queued=new Set(entries),seen=new Set(),referenced=new Set(entries),edges=[],files=[];let fetched=0;const MAX_TEXT=32,WAVE=4;
  while(queue.length&&fetched<MAX_TEXT){const wave=[];while(queue.length&&wave.length<WAVE&&fetched+wave.length<MAX_TEXT){const path=queue.shift();queued.delete(path);if(seen.has(path)||!treeSet.has(path)||!TEXT_EXT.test(path))continue;seen.add(path);const blob=blobMap.get(path);if(blob?.size>220000)continue;wave.push({path,blob});}if(!wave.length)continue;const texts=await Promise.all(wave.map(x=>fetchRaw(owner,repo,branch,x.path,env)));for(let i=0;i<wave.length;i++){const{path,blob}=wave[i],text=texts[i];if(text==null)continue;fetched++;files.push({path,size:blob?.size||text.length,content:text});for(const raw of extractRefs(path,text)){const to=resolveRef(path,raw,treeSet);if(!to)continue;edges.push({from:path,to,exists:treeSet.has(to)});if(treeSet.has(to)){referenced.add(to);if(TEXT_EXT.test(to)&&!seen.has(to)&&!queued.has(to)){queue.push(to);queued.add(to);}}}}}
  const unreachable=blobs.map(x=>x.path).filter(p=>!referenced.has(p)&&!/(?:^|\/)(?:node_modules|vendor|\.git)\//i.test(p));const signals=autoSignals(files,referenced,blobs);signals.treeTruncated=treeTruncated;signals.entryCount=entries.length;const sample=files.map(f=>`\n--- ${f.path} ---\n${f.content.slice(0,1800)}`).join('').slice(0,18000);
  return{repository:{owner,repo,description:meta.description,default_branch:branch,revision,updated_at:meta.updated_at,homepage:meta.homepage,language:meta.language,size:meta.size,fork:meta.fork,archived:meta.archived},entries,referenced:[...referenced].sort(),edges:edges.slice(0,500),unreachableCount:unreachable.length,unreachableSample:unreachable.slice(0,40),filesRead:files.map(f=>f.path),signals,sample,truncated:treeTruncated||queue.length>0};
}
async function getRepoSnapshot(repoUrl,env){const{owner,repo}=parseRepoUrl(repoUrl);return inspectRepo(owner,repo,env);}


function auditAllowed(url,env){try{const u=new URL(url);if(u.protocol!=='https:')return false;if(/\.github\.io$/i.test(u.hostname))return true;const extra=String(env.AUDIT_HOSTS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return extra.includes(u.hostname.toLowerCase());}catch{return false;}}
function siteTextRefs(text){const out=new Set();let m;const patterns=[/(?:href|src|data-src|poster)\s*=\s*["']([^"']+)["']/gi,/(?:fetch|window\.open|import)\s*\(\s*["']([^"']+)["']/gi,/(?:url\(|@import\s+)["']?([^"')\s;]+)["']?\)?/gi,/["']([^"'\n]{1,220}\.(?:html?|css|js|mjs|json|png|jpe?g|webp|gif|svg|ico|avif|woff2?|ttf|mp3|wav|ogg|mp4|webm|pdf)(?:[?#][^"']*)?)["']/gi];for(const re of patterns)while((m=re.exec(text)))out.add(m[1]);return[...out];}
async function auditSite(startUrl,env){if(!auditAllowed(startUrl,env))throw new Error('部署巡检仅允许 HTTPS GitHub Pages；其他域名需加入 Worker 的 AUDIT_HOSTS');const start=new URL(startUrl);const basePrefix=(()=>{const parts=start.pathname.split('/').filter(Boolean);return parts.length?`/${parts[0]}/`:'/';})();const queue=[start.href],seen=new Set(),items=[],broken=[],htmlPages=[],outsideBase=[],externalOrigins=new Set(),interaction={buttons:0,links:0,inputs:0,forms:0,clickHandlers:0,submitHandlers:0,dragDrop:false,touch:false,keyboard:false,locationChanges:0,storageWrites:0,absoluteRootRefs:0,emptyHref:0};const MAX_URLS=110,MAX_TEXT=45;
  let textReads=0;
  while(queue.length&&seen.size<MAX_URLS){const href=queue.shift();if(seen.has(href))continue;seen.add(href);let r;try{r=await fetchWithTimeout(href,{redirect:'follow',headers:{'User-Agent':'narrative-workshop-agent-site-audit'}},10000);}catch(e){broken.push({url:href,status:0,error:e.message});continue;}const ct=r.headers.get('content-type')||'',rec={url:href,status:r.status,contentType:ct};items.push(rec);if(!r.ok){broken.push(rec);continue;}const textual=/text\/(?:html|css|javascript)|application\/(?:javascript|json)/i.test(ct)||/\.(?:html?|css|js|mjs|json)(?:[?#]|$)/i.test(href);if(!textual||textReads>=MAX_TEXT)continue;const text=(await r.text()).slice(0,260000);textReads++;if(/text\/html/i.test(ct)||/\.html?(?:[?#]|$)/i.test(href)){htmlPages.push({url:href,title:(text.match(/<title[^>]*>([^<]*)<\/title>/i)||[])[1]?.trim()||'',bytes:text.length});}
    const sig=interactionSignals(text);for(const k of ['buttons','links','inputs','forms','clickHandlers','submitHandlers','locationChanges','storageWrites','absoluteRootRefs','emptyHref'])interaction[k]+=sig[k]||0;for(const k of ['dragDrop','touch','keyboard'])interaction[k]=interaction[k]||sig[k];
    for(const raw of siteTextRefs(text)){if(!raw||/^(?:mailto:|tel:|javascript:|data:|#)/i.test(raw))continue;let u;try{u=new URL(raw,href);}catch{continue;}if(u.origin!==start.origin){if(/^https?:/i.test(u.href))externalOrigins.add(u.origin);continue;}u.hash='';if(basePrefix!=='/'&&!u.pathname.startsWith(basePrefix)){outsideBase.push({from:href,ref:raw,resolved:u.href});continue;}if(!seen.has(u.href)&&queue.length+seen.size<MAX_URLS)queue.push(u.href);}
  }
  const warnings=[];if(interaction.absoluteRootRefs&&basePrefix!=='/')warnings.push(`检测到 ${interaction.absoluteRootRefs} 个根路径引用特征，GitHub Pages 子路径下可能 404`);if(interaction.buttons>0&&interaction.clickHandlers===0)warnings.push('检测到按钮但静态代码未发现 click 处理器；若事件通过框架绑定可忽略');if(interaction.forms>0&&interaction.submitHandlers===0)warnings.push('检测到表单但静态代码未发现 submit 处理器；需人工确认提交行为');
  return{start:start.href,basePrefix,checked:items.length,textRead:textReads,htmlPages,broken,outsideBase:outsideBase.slice(0,60),externalOrigins:[...externalOrigins].slice(0,30),interaction,warnings,ok:broken.length===0&&outsideBase.length===0,truncated:queue.length>0};
}
function compactText(v){return String(v||'').replace(/[\s\p{P}\p{S}]+/gu,'');}
function compactLen(v){return compactText(v).length;}
function serverMeaningful(v,min){const raw=String(v||'').trim(),c=compactText(raw);if(!raw||/^(无|暂无|待定|待完善|todo|tbd|none|测试|test|占位|xxx|n\/a)[\s。！!，,]*$/i.test(raw)||c.length<min)return false;const unique=new Set([...c]).size;if(unique<Math.min(18,Math.ceil(c.length*.06)))return false;if(/(.{1,6})\1{8,}/u.test(c))return false;return true;}
function serverEvidence(project={}){const rules={concept:[40,8],bible:[420,18],architecture:[360,14],puzzles:[300,14],copyPack:[650,16],visual:[260,10],qa:[260,12],deploy:[180,8]};let earned=0,total=0;const fields={};for(const[k,[min,weight]]of Object.entries(rules)){const v=String(project[k]||''),len=compactLen(v),valid=serverMeaningful(v,min),partial=!valid&&serverMeaningful(v,Math.max(24,Math.round(min*.3)));fields[k]={valid,partial,length:len,required:min,weight};total+=weight;earned+=valid?weight:partial?Math.round(weight*.35):0;}return{coverage:Math.min(100,Math.round(earned/total*100)),fields};}
function enforceReview(review,evidence){if(!review||typeof review!=='object')return review;let score=Number(review.score);if(evidence.coverage<35){review.score=null;}else if(!Number.isFinite(score)){review.score=null;}else{let cap=10;if(evidence.coverage<45)cap=5.5;else if(evidence.coverage<70)cap=7.5;if((review.blockers||[]).some(x=>x.severity==='P0'))cap=Math.min(cap,6.5);review.score=Math.max(0,Math.min(cap,score));}review.evidenceCoverage=evidence.coverage;return review;}

export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(request,env)});const url=new URL(request.url);if(url.pathname==='/health')return json(request,env,{ok:true,service:'webgame-agent',model:env.TEXT_MODEL||DEFAULT_TEXT_MODEL,imageModel:env.IMAGE_MODEL||DEFAULT_IMAGE_MODEL,github:!!env.GITHUB_TOKEN,auth:!!env.APP_SECRET});if(!authorized(request,env))return json(request,env,{error:'Agent Key 不正确'},401);
  try{
    if(url.pathname==='/api/ping')return json(request,env,{ok:true,service:'webgame-agent',model:env.TEXT_MODEL||DEFAULT_TEXT_MODEL,imageModel:env.IMAGE_MODEL||DEFAULT_IMAGE_MODEL,github:!!env.GITHUB_TOKEN,ai:!!env.AI,authenticated:true});
    if(url.pathname==='/api/github/repos'&&request.method==='POST'){const body=await readJson(request),owner=String(body.owner||'').trim();if(!/^[A-Za-z0-9-]{1,39}$/.test(owner))return json(request,env,{error:'GitHub owner 格式无效'},400);const repos=[];for(let page=1;page<=5;page++){const chunk=await ghFetch(`https://api.github.com/users/${owner}/repos?per_page=100&page=${page}&sort=updated&type=owner`,env);repos.push(...chunk);if(chunk.length<100)break;}return json(request,env,{repos:repos.map(r=>({name:r.name,url:r.html_url,description:r.description,updated_at:r.updated_at,language:r.language,archived:r.archived,fork:r.fork,size:r.size,homepage:r.homepage,has_pages:!!r.has_pages}))});}
    if(url.pathname==='/api/github/inspect'&&request.method==='POST'){const body=await readJson(request);const{owner,repo}=body.repoUrl?parseRepoUrl(body.repoUrl):{owner:String(body.owner||''),repo:String(body.repo||'')};if(!owner||!repo)return json(request,env,{error:'缺少 owner/repo'},400);return json(request,env,await withTimeout(inspectRepo(owner,repo,env),40000,`仓库 ${repo} 扫描`));}
    if(url.pathname==='/api/github/analyze'&&request.method==='POST'){const body=await readJson(request);const snapshot=await withTimeout(getRepoSnapshot(body.repoUrl,env),40000,'仓库依赖扫描');const result=await runText(env,buildPrompt('strict_review',{mode:'GitHub 仓库复盘（仅实际引用文件）',snapshot,project:body.project||null,experiences:body.experiences||[],instruction:'只依据入口可达依赖图和实际读取文件。unreachableSample 只能作为“疑似残留”而非作品事实。'}),{timeoutMs:95000});return json(request,env,{...result,snapshot});}
    if(url.pathname==='/api/review/blind'&&request.method==='POST'){const body=await readJson(request),repoUrl=String(body.repoUrl||'').trim();if(!repoUrl)return json(request,env,{error:'缺少主游戏 GitHub 仓库地址'},400);const snapshot=await withTimeout(getRepoSnapshot(repoUrl,env),45000,'盲复盘仓库扫描');const identity={title:String(body.identity?.title||snapshot.repository?.repo||'').slice(0,140),genres:Array.isArray(body.identity?.genres)?body.identity.genres.slice(0,4):[]};const first=await runJson(env,'blind_review_json',{snapshot,identity,blindRules:{postHocFeedback:false,projectChat:false,previousReview:false,portfolioSummary:false,projectExperiences:false}},{maxTokens:6800,timeoutMs:75000});let review=sanitizeBlindReview(first.data),verified=false,verifyError='';if(body.verify!==false){try{const second=await runJson(env,'blind_review_verify_json',{snapshot,identity,draft:review},{maxTokens:6800,timeoutMs:75000});review=sanitizeBlindReview(second.data);verified=true;}catch(e){verifyError=e?.message||'二次证据复核失败';}}if(snapshot.truncated||(snapshot.filesRead||[]).length<3)review.score=null;const evidence={repo:snapshot.repository?.repo||'',revision:snapshot.repository?.revision||'',updated_at:snapshot.repository?.updated_at||'',filesRead:(snapshot.filesRead||[]).length,referenced:(snapshot.referenced||[]).length,truncated:!!snapshot.truncated,entries:(snapshot.entries||[]).slice(0,12)};return json(request,env,{review,model:first.model,verified,verifyError,ruleVersion:'blind-v1.0',evidence});}
    if(url.pathname==='/api/site/audit'&&request.method==='POST'){const body=await readJson(request);const target=String(body.url||'').trim();if(!target)return json(request,env,{error:'缺少部署 URL'},400);return json(request,env,await auditSite(target,env));}
    if(url.pathname==='/api/genre/review'&&request.method==='POST'){const body=await readJson(request);const r=await runJson(env,'genre_analysis_json',{concept:body.concept,project:body.project||null});return json(request,env,{result:r.data,model:r.model});}
    if(url.pathname==='/api/copy/plan'&&request.method==='POST'){const body=await readJson(request);const r=await runJson(env,'copy_plan_json',{project:body.project,experiences:body.experiences||[]});return json(request,env,{plan:r.data,model:r.model});}
    if(url.pathname==='/api/copy/section'&&request.method==='POST'){const body=await readJson(request);const result=await runText(env,buildPrompt('copy_section',{project:body.project,section:body.section,completed:body.completed||[],experiences:body.experiences||[]}));return json(request,env,result);}
    if(url.pathname==='/api/review'&&request.method==='POST'){const body=await readJson(request),project=body.project||{},evidence=serverEvidence(project),reviewProject={...project,review:null,blindReviews:undefined,lastImage:undefined,chat:undefined};const r=await runJson(env,'strict_review_json',{project:reviewProject,evidence,experiences:body.experiences||[],portfolioAudit:body.portfolioAudit||null});return json(request,env,{review:enforceReview(r.data,evidence),model:r.model,ruleVersion:'strict-v2'});}
    if(url.pathname==='/api/experience/review'&&request.method==='POST'){const body=await readJson(request);const r=await runJson(env,'experience_review_json',{text:body.text,experiences:(body.experiences||[]).slice(0,90),project:body.project||null});return json(request,env,{review:r.data,model:r.model});}
    if(url.pathname==='/api/portfolio/catalog'&&request.method==='POST'){const body=await readJson(request),items=Array.isArray(body.items)?body.items.slice(0,24):[];if(!items.length)return json(request,env,{error:'没有可分类仓库'},400);const r=await runJson(env,'portfolio_catalog_json',{owner:String(body.owner||''),items});const out=Array.isArray(r.data?.items)?r.data.items.filter(x=>x&&typeof x.repo==='string').slice(0,items.length):[];return json(request,env,{items:out,model:r.model});}
    if(url.pathname==='/api/portfolio/match-main'&&request.method==='POST'){const body=await readJson(request),source=Array.isArray(body.source)?body.source.slice(0,12):[],candidates=Array.isArray(body.candidates)?body.candidates.filter(x=>x&&x.category!=='guide'&&x.category!=='old'&&x.category!=='test'&&x.category!=='tool').slice(0,60):[];if(!source.length||!candidates.length)return json(request,env,{error:'缺少待匹配仓库或主游戏候选'},400);const r=await runJson(env,'portfolio_match_main_json',{owner:String(body.owner||''),source,candidates});const allowed=new Set(candidates.map(x=>x.repo));const matches=Array.isArray(r.data?.matches)?r.data.matches.filter(x=>x&&typeof x.repo==='string'&&allowed.has(x.repo)).slice(0,6):[];return json(request,env,{matches,model:r.model});}
    if(url.pathname==='/api/ai'&&request.method==='POST'){const body=await readJson(request);if(!body.task)return json(request,env,{error:'缺少 task'},400);const prompt=buildPrompt(body.task,body.payload||{});const taskOpts=body.task==='portfolio_batch_review'?{maxTokens:2600,temperature:.25,timeoutMs:75000}:body.task==='portfolio_synthesis_chunk'?{maxTokens:2400,temperature:.2,timeoutMs:75000}:body.task==='portfolio_synthesis'?{maxTokens:4200,temperature:.22,timeoutMs:90000}:{};const result=await runText(env,prompt,taskOpts);return json(request,env,result);}
    if(url.pathname==='/api/image'&&request.method==='POST'){if(!env.AI)throw new Error('缺少 Workers AI binding');const body=await readJson(request),prompt=String(body.prompt||'').trim();if(!prompt)return json(request,env,{error:'缺少图片设计说明'},400);const model=env.IMAGE_MODEL||DEFAULT_IMAGE_MODEL;const full=`叙事解谜游戏素材。先服从作品世界内来源、年代、设备和用途，避免AI宣传海报感、完美对称和无理由电影化。${prompt}`.slice(0,2400);const result=await withTimeout(env.AI.run(model,{prompt:full,steps:6}),75000,'图片生成');if(!result?.image)return json(request,env,{error:'图像模型未返回 image；如更换 IMAGE_MODEL，请同步适配参数格式'},502);return json(request,env,{dataURI:`data:image/jpeg;base64,${result.image}`,model});}
    return json(request,env,{error:'Not found'},404);
  }catch(err){return json(request,env,{error:err?.message||'Worker error'},500);}
}};
