import { buildPrompt } from './prompts.js';

const DEFAULT_TEXT_MODEL='@cf/zai-org/glm-4.7-flash';
const DEFAULT_IMAGE_MODEL='@cf/black-forest-labs/flux-1-schnell';
const MAX_BODY=900_000;
const TEXT_EXT=/\.(?:html?|css|js|mjs|cjs|ts|tsx|jsx|json|md|txt|xml|csv)$/i;
const ASSET_EXT=/\.(?:html?|css|js|mjs|cjs|ts|tsx|jsx|json|md|txt|xml|csv|png|jpe?g|webp|gif|svg|ico|avif|woff2?|ttf|mp3|wav|ogg|mp4|webm|pdf)$/i;

function corsHeaders(request,env){const origin=request.headers.get('Origin')||'';const allowed=String(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);const ok=!allowed.length||allowed.includes(origin)||/^https:\/\/[^/]+\.github\.io$/.test(origin)||/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);return{'Access-Control-Allow-Origin':ok?(origin||'*'):'null','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Agent-Key','Access-Control-Max-Age':'86400','Vary':'Origin','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};}
function json(request,env,data,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders(request,env),'content-type':'application/json; charset=utf-8'}});}
function authorized(request,env){return !env.APP_SECRET||request.headers.get('X-Agent-Key')===env.APP_SECRET;}
async function readJson(request){const len=Number(request.headers.get('content-length')||0);if(len>MAX_BODY)throw new Error('请求过大');const text=await request.text();if(text.length>MAX_BODY)throw new Error('请求过大');return text?JSON.parse(text):{};}
function getText(result){if(!result)return'';if(typeof result==='string')return result;if(typeof result.response==='string')return result.response;if(typeof result.result==='string')return result.result;const c=result.choices?.[0]?.message?.content;if(typeof c==='string')return c;if(Array.isArray(c))return c.map(x=>x.text||x.content||'').join('');return JSON.stringify(result,null,2);}
async function runText(env,prompt,opts={}){if(!env.AI)throw new Error('缺少 Workers AI binding：请在 wrangler.jsonc 配置 AI');const model=env.TEXT_MODEL||DEFAULT_TEXT_MODEL;const messages=[{role:'system',content:'你是专门服务网页叙事解谜制作流程的专业 Agent。严格遵守项目方法论，拒绝模板化空话。'},{role:'user',content:prompt}];const result=await env.AI.run(model,{messages,max_completion_tokens:opts.maxTokens||Number(env.MAX_TOKENS)||9000,temperature:opts.temperature??0.45});return{text:getText(result),model};}
function parseJsonText(text){let t=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(t);}catch{}const a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a){try{return JSON.parse(t.slice(a,b+1));}catch{}}return null;}
async function runJson(env,task,payload){const r=await runText(env,buildPrompt(task,payload),{temperature:.2,maxTokens:7000});const data=parseJsonText(r.text);if(!data)throw new Error('AI 未返回有效结构化 JSON');return{data,model:r.model};}

function parseRepoUrl(url){const m=String(url||'').match(/^https?:\/\/github\.com\/([^/]+)\/([^/#?]+)(?:[/?#].*)?$/i);if(!m)throw new Error('仅支持标准 GitHub 仓库地址');return{owner:m[1],repo:m[2].replace(/\.git$/,'')};}
function ghHeaders(env){const h={'Accept':'application/vnd.github+json','User-Agent':'narrative-workshop-agent','X-GitHub-Api-Version':'2022-11-28'};if(env.GITHUB_TOKEN)h.Authorization=`Bearer ${env.GITHUB_TOKEN}`;return h;}
async function ghFetch(url,env){const r=await fetch(url,{headers:ghHeaders(env)});if(!r.ok){const t=await r.text();throw new Error(`GitHub API ${r.status}: ${t.slice(0,180)}`);}return r.json();}
function encPath(path){return path.split('/').map(encodeURIComponent).join('/');}
function dirname(path){const i=path.lastIndexOf('/');return i<0?'':path.slice(0,i);}
function normalizePath(path){const out=[];for(const part of String(path).split('/')){if(!part||part==='.')continue;if(part==='..')out.pop();else out.push(part);}return out.join('/');}
function resolveRef(from,ref,treeSet){let raw=String(ref||'').trim();if(!raw||/^(?:https?:|data:|mailto:|tel:|javascript:|#|\/\/)/i.test(raw))return null;raw=raw.replace(/[?#].*$/,'').replace(/^\.\//,'');try{raw=decodeURIComponent(raw);}catch{}let p=raw.startsWith('/')?raw.slice(1):normalizePath(`${dirname(from)}/${raw}`);if(treeSet.has(p))return p;if(treeSet.has(`${p}/index.html`))return`${p}/index.html`;return p&&ASSET_EXT.test(p)?p:null;}
function extractRefs(path,text){const refs=new Set();const add=x=>{if(x&&x.length<500)refs.add(x.trim())};let m;
  const attrs=/(?:src|href|data-src|poster|content)\s*=\s*["']([^"']+)["']/gi;while((m=attrs.exec(text)))add(m[1]);
  const imports=/(?:import\s*(?:[^'"()]+?\sfrom\s*)?|import\s*\(|require\s*\(|fetch\s*\(|window\.open\s*\(|location(?:\.href)?\s*=)\s*["']([^"']+)["']/gi;while((m=imports.exec(text)))add(m[1]);
  const css=/(?:url\(|@import\s+)["']?([^"')\s;]+)["']?\)?/gi;while((m=css.exec(text)))add(m[1]);
  const strings=/["']([^"'\n]{1,220}\.(?:html?|css|js|mjs|ts|json|png|jpe?g|webp|gif|svg|ico|avif|woff2?|ttf|mp3|wav|ogg|mp4|webm|pdf)(?:[?#][^"']*)?)["']/gi;while((m=strings.exec(text)))add(m[1]);
  return [...refs];
}
async function getRepoBase(owner,repo,env){const meta=await ghFetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`,env);const branch=meta.default_branch||'main';const tree=await ghFetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/trees/${encodeURIComponent(branch)}?recursive=1`,env);const blobs=(tree.tree||[]).filter(x=>x.type==='blob');return{meta,branch,blobs};}
async function fetchRaw(owner,repo,branch,path){const u=`https://raw.githubusercontent.com/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/${encodeURIComponent(branch)}/${encPath(path)}`;const r=await fetch(u,{headers:{'User-Agent':'narrative-workshop-agent'}});if(!r.ok)return null;return(await r.text()).slice(0,120000);}
function chooseEntries(blobs){const paths=blobs.map(x=>x.path);const entries=[];for(const c of ['index.html','index.htm','docs/index.html','public/index.html','src/index.html'])if(paths.includes(c))entries.push(c);if(!entries.length)entries.push(...paths.filter(p=>/^[^/]+\.html?$/i.test(p)).slice(0,4));return[...new Set(entries)];}
function autoSignals(files,referenced,blobs){const joined=files.map(f=>f.content).join('\n');return{reachableTextFiles:files.length,referencedFiles:referenced.size,totalRepoFiles:blobs.length,htmlFiles:[...referenced].filter(x=>/\.html?$/i.test(x)).length,cssFiles:[...referenced].filter(x=>/\.css$/i.test(x)).length,imageFiles:[...referenced].filter(x=>/\.(?:png|jpe?g|webp|gif|svg|avif)$/i.test(x)).length,hasResponsive:/@media\s*\(/i.test(joined),hasLocalStorage:/localStorage|sessionStorage|indexedDB/i.test(joined),hasPayment:/付款|支付|二维码|donate|payment/i.test(joined),hasGlitch:/glitch|故障|噪点|scanline/i.test(joined),hasLockedLanguage:/未解锁|第[一二三四五六七八九十\d]+章|完成上一关/.test(joined),hasAiCliche:/你不该来这里|有些事情最好不要知道|真相从未消失/.test(joined),titles:[...joined.matchAll(/<title[^>]*>([^<]{1,100})<\/title>/gi)].slice(0,8).map(m=>m[1].trim())};}
async function inspectRepo(owner,repo,env){const{meta,branch,blobs}=await getRepoBase(owner,repo,env);const treeSet=new Set(blobs.map(x=>x.path));const entries=chooseEntries(blobs);const queue=[...entries],seen=new Set(),referenced=new Set(entries),edges=[],files=[];let fetched=0;const MAX_TEXT=32;
  while(queue.length&&fetched<MAX_TEXT){const path=queue.shift();if(seen.has(path)||!treeSet.has(path)||!TEXT_EXT.test(path))continue;seen.add(path);const blob=blobs.find(x=>x.path===path);if(blob?.size>220000)continue;const text=await fetchRaw(owner,repo,branch,path);if(text==null)continue;fetched++;files.push({path,size:blob?.size||text.length,content:text});for(const raw of extractRefs(path,text)){const to=resolveRef(path,raw,treeSet);if(!to)continue;edges.push({from:path,to,exists:treeSet.has(to)});if(treeSet.has(to)){referenced.add(to);if(TEXT_EXT.test(to)&&!seen.has(to))queue.push(to);}}
  }
  const unreachable=blobs.map(x=>x.path).filter(p=>!referenced.has(p)&&!/(?:^|\/)(?:node_modules|vendor|\.git)\//i.test(p));const signals=autoSignals(files,referenced,blobs);const sample=files.map(f=>`\n--- ${f.path} ---\n${f.content.slice(0,1800)}`).join('').slice(0,18000);
  return{repository:{owner,repo,description:meta.description,default_branch:branch,updated_at:meta.updated_at,homepage:meta.homepage,language:meta.language,size:meta.size,fork:meta.fork,archived:meta.archived},entries,referenced:[...referenced].sort(),edges:edges.slice(0,500),unreachableCount:unreachable.length,unreachableSample:unreachable.slice(0,40),filesRead:files.map(f=>f.path),signals,sample};
}
async function getRepoSnapshot(repoUrl,env){const{owner,repo}=parseRepoUrl(repoUrl);return inspectRepo(owner,repo,env);}


function auditAllowed(url,env){try{const u=new URL(url);if(u.protocol!=='https:')return false;if(/\.github\.io$/i.test(u.hostname))return true;const extra=String(env.AUDIT_HOSTS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return extra.includes(u.hostname.toLowerCase());}catch{return false;}}
function siteRefs(html){const out=new Set();let m;const re=/(?:href|src|data-src|poster)\s*=\s*["']([^"']+)["']/gi;while((m=re.exec(html)))out.add(m[1]);return[...out];}
async function auditSite(startUrl,env){if(!auditAllowed(startUrl,env))throw new Error('部署巡检仅允许 HTTPS GitHub Pages；其他域名需加入 Worker 的 AUDIT_HOSTS');const start=new URL(startUrl);const basePrefix=(()=>{const parts=start.pathname.split('/').filter(Boolean);return parts.length?`/${parts[0]}/`:'/';})();const queue=[start.href],seen=new Set(),items=[],broken=[],htmlPages=[],outsideBase=[];const MAX_URLS=80,MAX_HTML=30;
  while(queue.length&&seen.size<MAX_URLS){const href=queue.shift();if(seen.has(href))continue;seen.add(href);let r;try{r=await fetch(href,{redirect:'follow',headers:{'User-Agent':'narrative-workshop-agent-site-audit'}});}catch(e){broken.push({url:href,status:0,error:e.message});continue;}const ct=r.headers.get('content-type')||'';const rec={url:href,status:r.status,contentType:ct};items.push(rec);if(!r.ok){broken.push(rec);continue;}if(ct.includes('text/html')&&htmlPages.length<MAX_HTML){const text=(await r.text()).slice(0,250000);htmlPages.push({url:href,title:(text.match(/<title[^>]*>([^<]*)<\/title>/i)||[])[1]?.trim()||'',bytes:text.length});for(const raw of siteRefs(text)){if(!raw||/^(?:mailto:|tel:|javascript:|data:|#)/i.test(raw))continue;let u;try{u=new URL(raw,href);}catch{continue;}if(u.origin!==start.origin)continue;u.hash='';if(basePrefix!=='/'&&!u.pathname.startsWith(basePrefix)){outsideBase.push({from:href,ref:raw,resolved:u.href});continue;}const key=u.href;if(!seen.has(key)&&queue.length+seen.size<MAX_URLS)queue.push(key);}}
  }
  return{start:start.href,basePrefix,checked:items.length,htmlPages,broken,outsideBase:outsideBase.slice(0,40),ok:broken.length===0&&outsideBase.length===0,truncated:queue.length>0};
}

function compactText(v){return String(v||'').replace(/[\s\p{P}\p{S}]+/gu,'');}
function compactLen(v){return compactText(v).length;}
function serverMeaningful(v,min){const raw=String(v||'').trim(),c=compactText(raw);if(!raw||/^(无|暂无|待定|待完善|todo|tbd|none|测试|test|占位|xxx|n\/a)[\s。！!，,]*$/i.test(raw)||c.length<min)return false;const unique=new Set([...c]).size;if(unique<Math.min(18,Math.ceil(c.length*.06)))return false;if(/(.{1,6})\1{8,}/u.test(c))return false;return true;}
function serverEvidence(project={}){const rules={concept:[40,8],bible:[420,18],architecture:[360,14],puzzles:[300,14],copyPack:[650,16],visual:[260,10],qa:[260,12],deploy:[180,8]};let earned=0,total=0;const fields={};for(const[k,[min,weight]]of Object.entries(rules)){const v=String(project[k]||''),len=compactLen(v),valid=serverMeaningful(v,min),partial=!valid&&serverMeaningful(v,Math.max(24,Math.round(min*.3)));fields[k]={valid,partial,length:len,required:min,weight};total+=weight;earned+=valid?weight:partial?Math.round(weight*.35):0;}return{coverage:Math.min(100,Math.round(earned/total*100)),fields};}
function enforceReview(review,evidence){if(!review||typeof review!=='object')return review;let score=Number(review.score);if(evidence.coverage<35){review.score=null;}else if(!Number.isFinite(score)){review.score=null;}else{let cap=10;if(evidence.coverage<45)cap=5.5;else if(evidence.coverage<70)cap=7.5;if((review.blockers||[]).some(x=>x.severity==='P0'))cap=Math.min(cap,6.5);review.score=Math.max(0,Math.min(cap,score));}review.evidenceCoverage=evidence.coverage;return review;}

export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(request,env)});const url=new URL(request.url);if(url.pathname==='/health')return json(request,env,{ok:true,service:'narrative-workshop-agent',model:env.TEXT_MODEL||DEFAULT_TEXT_MODEL,imageModel:env.IMAGE_MODEL||DEFAULT_IMAGE_MODEL,github:!!env.GITHUB_TOKEN,auth:!!env.APP_SECRET});if(!authorized(request,env))return json(request,env,{error:'Agent Key 不正确'},401);
  try{
    if(url.pathname==='/api/github/repos'&&request.method==='POST'){const body=await readJson(request),owner=String(body.owner||'').trim();if(!/^[A-Za-z0-9-]{1,39}$/.test(owner))return json(request,env,{error:'GitHub owner 格式无效'},400);const repos=await ghFetch(`https://api.github.com/users/${owner}/repos?per_page=100&sort=updated&type=owner`,env);return json(request,env,{repos:repos.map(r=>({name:r.name,url:r.html_url,description:r.description,updated_at:r.updated_at,language:r.language,archived:r.archived,fork:r.fork,size:r.size,homepage:r.homepage}))});}
    if(url.pathname==='/api/github/inspect'&&request.method==='POST'){const body=await readJson(request);const{owner,repo}=body.repoUrl?parseRepoUrl(body.repoUrl):{owner:String(body.owner||''),repo:String(body.repo||'')};if(!owner||!repo)return json(request,env,{error:'缺少 owner/repo'},400);return json(request,env,await inspectRepo(owner,repo,env));}
    if(url.pathname==='/api/github/analyze'&&request.method==='POST'){const body=await readJson(request);const snapshot=await getRepoSnapshot(body.repoUrl,env);const result=await runText(env,buildPrompt('strict_review',{mode:'GitHub 仓库复盘（仅实际引用文件）',snapshot,project:body.project||null,experiences:body.experiences||[],instruction:'只依据入口可达依赖图和实际读取文件。unreachableSample 只能作为“疑似残留”而非作品事实。'}));return json(request,env,{...result,snapshot});}
    if(url.pathname==='/api/site/audit'&&request.method==='POST'){const body=await readJson(request);const target=String(body.url||'').trim();if(!target)return json(request,env,{error:'缺少部署 URL'},400);return json(request,env,await auditSite(target,env));}
    if(url.pathname==='/api/genre/review'&&request.method==='POST'){const body=await readJson(request);const r=await runJson(env,'genre_analysis_json',{concept:body.concept,project:body.project||null});return json(request,env,{result:r.data,model:r.model});}
    if(url.pathname==='/api/copy/plan'&&request.method==='POST'){const body=await readJson(request);const r=await runJson(env,'copy_plan_json',{project:body.project,experiences:body.experiences||[]});return json(request,env,{plan:r.data,model:r.model});}
    if(url.pathname==='/api/copy/section'&&request.method==='POST'){const body=await readJson(request);const result=await runText(env,buildPrompt('copy_section',{project:body.project,section:body.section,completed:body.completed||[],experiences:body.experiences||[]}));return json(request,env,result);}
    if(url.pathname==='/api/review'&&request.method==='POST'){const body=await readJson(request),project=body.project||{},evidence=serverEvidence(project),reviewProject={...project,review:null,lastImage:undefined,chat:undefined};const r=await runJson(env,'strict_review_json',{project:reviewProject,evidence,experiences:body.experiences||[],portfolioAudit:body.portfolioAudit||null});return json(request,env,{review:enforceReview(r.data,evidence),model:r.model});}
    if(url.pathname==='/api/experience/review'&&request.method==='POST'){const body=await readJson(request);const r=await runJson(env,'experience_review_json',{text:body.text,experiences:(body.experiences||[]).slice(0,90),project:body.project||null});return json(request,env,{review:r.data,model:r.model});}
    if(url.pathname==='/api/ai'&&request.method==='POST'){const body=await readJson(request);if(!body.task)return json(request,env,{error:'缺少 task'},400);const prompt=buildPrompt(body.task,body.payload||{});const result=await runText(env,prompt);return json(request,env,result);}
    if(url.pathname==='/api/image'&&request.method==='POST'){if(!env.AI)throw new Error('缺少 Workers AI binding');const body=await readJson(request),prompt=String(body.prompt||'').trim();if(!prompt)return json(request,env,{error:'缺少图片设计说明'},400);const model=env.IMAGE_MODEL||DEFAULT_IMAGE_MODEL;const full=`叙事解谜游戏素材。先服从作品世界内来源、年代、设备和用途，避免AI宣传海报感、完美对称和无理由电影化。${prompt}`.slice(0,2400);const result=await env.AI.run(model,{prompt:full,steps:6});if(!result?.image)return json(request,env,{error:'图像模型未返回 image；如更换 IMAGE_MODEL，请同步适配参数格式'},502);return json(request,env,{dataURI:`data:image/jpeg;base64,${result.image}`,model});}
    return json(request,env,{error:'Not found'},404);
  }catch(err){return json(request,env,{error:err?.message||'Worker error'},500);}
}};
